### ISSUE TITLE
No Package found named "Nord"

### ISSUE THREAD

**Issue by FranzSw** [arcticicestudio/nord-sublime-text#11]
Currently, it seems like there is no package called "Nord" on packagecontrol.io
https://packagecontrol.io/search/Nord

**Comment by epistrephein** [comment]
#7

**Comment by FranzSw** [comment]
Well thanks...

**Comment by arcticicestudio** [comment]
> Duplicate of #7

I admit that the install instructions might be a bit confusing, but that's why the main branch of the project is `develop`. As soon as the first version has been released it'll be merged into `master` which is the stable project branch where all version tags get merged into.

**Comment by FranzSw** [comment]
Yesss, my bad, didn't see I was on the develop branch :)
