### ISSUE TITLE
Nord is not available in sublime package control

### ISSUE THREAD

**Issue by gregorylearns** [arcticicestudio/nord-sublime-text#26]
![image](https://user-images.githubusercontent.com/34886930/66362401-350e6900-e9b5-11e9-966d-adbe69da0b8b.png)
https://packagecontrol.io/packages/Nord
Nord not available in Sublime package control.

I just want to thank you guys for maintaining and developing this elegant color scheme.

**Comment by arcticicestudio** [comment]
Duplicates #7 #10 #11 #12 #13

Hi @gregorylearns :wave:, thanks for your contribution :+1:

This is a known "problem", please see #7 or  #16 for more details.

>The initial package version [0.1.0][] has finally been released and deployed to the _Package Control_ registry through https://github.com/wbond/package_control_channel/pull/7652 :tada: 
>The PR is still pending, but the automatic tests already passed successfully and it should be reviewed quickly.
>
>:arrow_right: The theme will be available as new package named :snowflake: [Nord][pc].
>
>The project also migrated like all other ports to the [new and shiny website][web] for a clean appearance and code base and a way simpler maintenance and development workflow.

[0.1.0]: https://github.com/arcticicestudio/nord-sublime-text/releases/tag/v0.1.0
[web]: https://www.nordtheme.com/ports/sublime-text
[pc]: https://packagecontrol.io/packages/Nord
