### ISSUE TITLE
JSON/Comments/Strings syntax highlighting is broken

### ISSUE THREAD

**Issue by lukakerr** [arcticicestudio/nord-sublime-text#3]
Just in the past few days the syntax highlighting for JSON, variables (consts, lets), comments and strings has broken. 

I've copied over the exact .tmTheme file and selected it as the UI Color Scheme. For other themes it is working, just not for the nord theme

I've attached a screenshot from sublime of what I mean:

![screen shot 2017-12-07 at 1 50 07 pm](https://user-images.githubusercontent.com/20056300/33696276-9aa0a6c2-db55-11e7-9547-b8f7faec367b.png)

**Comment by lukakerr** [comment]
For strings, it seems to break around here: https://github.com/arcticicestudio/nord-sublime-text/blob/feature/gh-1-color-scheme/Nord.tmTheme#L644

For variables (constants, lets etc), it seems to break around here: https://github.com/arcticicestudio/nord-sublime-text/blob/feature/gh-1-color-scheme/Nord.tmTheme#L783

For comments, it seems to break around here: https://github.com/arcticicestudio/nord-sublime-text/blob/feature/gh-1-color-scheme/Nord.tmTheme#L110

**Comment by arcticicestudio** [comment]
I've tried to reproduce your screenshot but it works fine on my side.
I've created a `test.js` file and used the default *JavaScript* syntax highlighting and also tested it with the [Babel][b] package. 

![gh-3-scrot-negative-reproduction](https://user-images.githubusercontent.com/7836623/33704581-58030bf2-db2d-11e7-8e11-1d5154b29521.png)

* Which Sublime Text version are you running?
* Have you made sure to set the syntax e.g. to *JavaScript* to make sure the correct highlighting is used?
* Are there any packages installed which may take precedence regarding the highlighting?

[b]: https://packagecontrol.io/packages/Babel

**Comment by lukakerr** [comment]
Sublime Text version: 3143

Yes the correct language is selected. It happens across multiple languages (typescript, python, json)

I tried disabling all packages and restarting but it had no affect.

It started occurring as soon as I restored my laptop from a time machine backup, so I think this might something to do with it, although I'm not sure what have could affected it. I will do a complete uninstall including the Application Support directory and see how that goes

**Comment by lukakerr** [comment]
I followed this https://www.sublimetext.com/docs/3/revert.html to restore to a fresh state, and also deleted and re installed the application but it still doesnt work. Ive restarted my computer, and have no idea what could be causing it

**Comment by lukakerr** [comment]
Nevermind, I re installed again and it's working now. Have no idea why.. Thanks anyway! I'll close

**Comment by arcticicestudio** [comment]
Strange error, maybe related to a time machine backup problem. Anyway nice to hear you solved it.

**Comment by lee-hyunkyu** [comment]
@arcticicestudio I'm having a similar issue. I've restored to a fresh state and reinstalled sublime text several times.  However for things like method modifiers and comments, the syntax coloring seems to be broken. 
<img width="1042" alt="screen shot 2018-01-16 at 4 30 37 pm" src="https://user-images.githubusercontent.com/6354012/35019229-9528417e-fada-11e7-98f2-cae847208317.png">
