### ISSUE TITLE
what is the font of the preview?

### ISSUE THREAD

**Issue by ghost** [arcticicestudio/nord-sublime-text#32]
the display font is beautiful and I want to use it.

**Comment by arcticicestudio** [comment]
Hi @NwRq :wave:

It is the well-known font family [Source Code Pro][1] with `medium` weight.

[1]: https://github.com/adobe-fonts/source-code-pro

**Comment by arcticicestudio** [comment]
Based on your emoji reaction on my previous comment I guess this issue can be considered done 😄
