### ISSUE TITLE
Package missing from Package Control

### ISSUE THREAD

**Issue by mgomes** [arcticicestudio/nord-sublime-text#7]
I'm unable to locate the package by typing `Nord` into the Package Control installer. The link to the package via the README returns a 404: https://packagecontrol.io/packages/Nord

Thanks for your help 😬

**Comment by ghost** [comment]
It isn't available yet because you're on the develop branch, it won't be available on http://packagecontrol.io until it's merged to master.

You can install it manually until then.

**Comment by mgomes** [comment]
Oops, I was linked from another GH Issue and didn't pay attention to the branch. Thanks :+1:

**Comment by arcticicestudio** [comment]
The initial package version [0.1.0][] has finally been released and deployed to the _Package Control_ registry through https://github.com/wbond/package_control_channel/pull/7652 :tada: 
The PR is still pending, but the automatic tests already passed successfully and it should be reviewed quickly.

:arrow_right: The theme will be available as new package named :snowflake: [Nord][pc].

The project also migrated like all other ports to the [new and shiny website][web] for a clean appearance and code base and a way simpler maintenance and development workflow.

[0.1.0]: https://github.com/arcticicestudio/nord-sublime-text/releases/tag/v0.1.0
[web]: https://www.nordtheme.com/ports/sublime-text
[pc]: https://packagecontrol.io/packages/Nord

**Comment by crispgm** [comment]
Still no merge, PackageControl seems to be out of maintenance :)

**Comment by arcticicestudio** [comment]
The last commit was 3 days ago, so it seems like the project is still active, but I don't know how they decide when to merge/review which PR. The PR for Nord is really small and doesn't require any special handling like defining dependencies to other packages so unfortunately I've no way to speed up the process 😟

**Comment by arcticicestudio** [comment]
Good news: The PR has been merged and Nord Sublime Text is finally available from the _package control_ registry :tada: 

:bird: https://twitter.com/arcticicestudio/status/1191794445148180480 :bird:
